### ISSUE TITLE
Reduce code duplication

### ISSUE THREAD

**Issue by stalniy** [nraboy/ng2-cordova-oauth#13]
So, there are 2 goals:
- [ ] reduce code duplication through inheritance
- [ ] add support for LinkedIn provider (this one is in separate issue)

Let me know if that sounds good. I will create an appropriate MRs

**Comment by nraboy** [comment]
LinkedIn would be nice, but code reduction might not be possible.  It is an issue I faced with the first ng-cordova-oauth because even though oauth 1.0a and 2.0 are a standard, not all providers follow it the same.  Trying to build a one size fits all solution with minimal code didn't work for that reason.

**Comment by stalniy** [comment]
@nraboy In case if there is a need a child class can override parent's one. So, I don't see any issues with this

**Comment by nraboy** [comment]
@stalniy I am interested.  Can you whip this up and push it to the `development` branch?  We'll collaborate and make it good and get more providers added

**Comment by stalniy** [comment]
@nraboy this is how I'd like to see this library eventually: https://github.com/stalniy/ng2-cordova-oauth/tree/stable

Let me know if you would like see this merged in to your repo.

**Comment by nraboy** [comment]
Merged to the development branch.
